plugins:
  - module: s3
    class: S3
  - module: s3
    class: S3ACL
  - module: s3
    class: S3Glacier
  - module: iam
    class: IAM
  - module: kms
    class: KMS
  - module: secretsmanager
    class: SecretsManager
  - module: eventbridge
    class: EventBus
  - module: lambda
    class: LambdaResource
  - module: sqs
    class: SQS