plugins:
  - module: dynamodb
    class: DynamoDBTable
  - module: dynamodb
    class: DynamoDBStreams
  - module: efs
    class: EFSResource
  - module: eventbridge
    class: EventBus
  - module: iam
    class: IAM
  - module: kinesis
    class: Kinesis
  - module: kms
    class: KMS
  - module: lambda
    class: LambdaResource
  - module: opensearch
    class: OpenSearch
  - module: s3
    class: S3
  - module: s3
    class: S3ACL
  - module: s3
    class: S3Glacier
  - module: secretsmanager
    class: SecretsManager
  - module: sns
    class: SNS
  - module: sqs
    class: SQS
  - module: vpc
    class: VPCEndpoint